packages:
  - packages/*
  - tooling/*
  - apps/*
catalogs:
  default:
    "@ai-sdk/anthropic": beta
    "@ai-sdk/deepseek": beta
    "@ai-sdk/openai": beta
    "@ai-sdk/react": beta
    "@aws-sdk/client-s3": ^3.932.0
    "@aws-sdk/s3-request-presigner": ^3.932.0
    "@babel/preset-react": ^7.28.5
    "@babel/preset-typescript": ^7.28.5
    "@base-ui-components/react": ^1.0.0-beta.4
    "@better-auth/cli": 1.3.34
    "@better-auth/stripe": ^1.3.34
    "@biomejs/biome": ^2.3.5
    "@clack/prompts": ^0.11.0
    "@cloudflare/vite-plugin": ^1.14.2
    "@daveyplate/better-auth-ui": ^3.2.9
    "@e2b/code-interpreter": ^2.2.0
    "@hookform/resolvers": ^5.2.2
    "@icons-pack/react-simple-icons": ^13.8.0
    "@mrleebo/prisma-ast": ^0.13.1
    "@neondatabase/serverless": ^1.0.2
    "@openrouter/ai-sdk-provider": ^1.2.3
    "@orpc/client": ^1.11.2
    "@orpc/server": ^1.11.2
    "@orpc/tanstack-query": ^1.11.2
    "@phosphor-icons/react": ^2.1.10
    "@prisma/client": ^6.19.0
    "@react-email/components": ^1.0.1
    "@shikijs/transformers": ^3.15.0
    "@stripe/stripe-js": ^8.4.0
    "@t3-oss/env-nextjs": ^0.13.8
    "@tailwindcss/container-queries": ^0.1.1
    "@tailwindcss/postcss": ^4.1.17
    "@tailwindcss/vite": ^4.1.17
    "@tanstack/devtools-vite": ^0.3.11
    "@tanstack/react-devtools": ^0.8.1
    "@tanstack/react-query": ^5.90.9
    "@tanstack/react-router": ^1.136.4
    "@tanstack/react-router-devtools": ^1.136.4
    "@tanstack/react-router-ssr-query": ^1.136.4
    "@tanstack/react-start": ^1.136.4
    "@tanstack/react-table": ^8.21.3
    "@tanstack/react-virtual": ^3.13.12
    "@tanstack/router-plugin": ^1.136.4
    "@testing-library/dom": ^10.4.1
    "@testing-library/react": ^16.3.0
    "@types/better-sqlite3": ^7.6.13
    "@types/canvas-confetti": ^1.9.0
    "@types/fs-extra": ^11.0.4
    "@types/mdx": ^2.0.13
    "@types/node": ^24.10.1
    "@types/pg": ^8.15.6
    "@types/prompts": ^2.4.9
    "@types/react": ^19.2.5
    "@types/react-dom": ^19.2.3
    "@types/semver": ^7.7.1
    "@upstash/redis": ^1.35.6
    "@vercel/blob": ^2.0.0
    "@vercel/kv": ^3.0.0
    "@vercel/postgres": ^0.10.0
    "@vitejs/plugin-react": ^5.1.1
    "@vitest/ui": ^4.0.9
    ai: beta
    babel-plugin-react-compiler: ^1.0.0
    better-auth: ^1.3.34
    better-sqlite3: ^12.4.1
    c12: ^3.3.2
    canvas-confetti: ^1.9.4
    chalk: ^5.6.2
    chokidar: ^4.0.3
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    cmdk: ^1.1.1
    commander: ^14.0.2
    consola: ^3.4.2
    date-fns: ^4.1.0
    dotenv: ^17.2.3
    dotenv-cli: ^11.0.0
    drizzle-kit: ^0.31.7
    drizzle-orm: ^0.44.7
    drizzle-zod: ^0.8.3
    embla-carousel-react: ^8.6.0
    fast-glob: ^3.3.3
    figlet: ^1.9.4
    fs-extra: ^11.3.2
    fumadocs-core: ^16.0.11
    fumadocs-mdx: ^13.0.8
    fumadocs-typescript: ^4.0.13
    fumadocs-ui: ^16.0.11
    get-tsconfig: ^4.13.0
    harden-react-markdown: ^1.1.5
    hono: ^4.10.6
    html-to-image: ^1.11.13
    input-otp: ^1.4.2
    ioredis: ^5.8.2
    jiti: ^2.6.1
    jsdom: ^27.2.0
    katex: ^0.16.25
    kysely: ^0.28.8
    lucide-react: ^0.553.0
    mongodb: ^7.0.0
    motion: ^12.23.24
    mysql2: ^3.15.3
    nanoid: ^5.1.6
    next: ^16.0.3
    next-intl: ^4.5.3
    next-themes: ^0.4.6
    pathe: ^2.0.3
    pg: ^8.16.3
    postcss: ^8.5.6
    prettier: ^3.6.2
    prisma: ^6.19.0
    prompts: ^2.4.2
    qrcode.react: ^4.2.0
    react: ^19.2.0
    react-day-picker: ^9.11.1
    react-dom: ^19.2.0
    react-email: 5.0.4
    react-fast-compare: ^3.2.2
    react-hook-form: ^7.66.0
    react-markdown: ^10.1.0
    react-resizable-panels: ^3.0.6
    recharts: 3.4.1
    redis: ^5.9.0
    refractor: ^5.0.0
    rehype-katex: ^7.0.1
    remark-gfm: ^4.0.1
    remark-math: ^6.0.0
    resend: ^6.4.2
    rough-notation: ^0.5.1
    semver: ^7.7.3
    server-only: ^0.0.1
    shadcn: ^3.5.0
    shiki: ^3.15.0
    sonner: ^2.0.7
    std-env: ^3.10.0
    streamdown: ^1.4.0
    stripe: ^19.3.1
    tailwind-merge: ^3.4.0
    tailwindcss: 4.1.17
    tailwindcss-animate: ^1.0.7
    taze: ^19.9.0
    tokenlens: ^1.3.1
    ts-pattern: ^5.9.0
    tsdown: ^0.16.4
    tsx: ^4.20.6
    turbo: ^2.6.1
    tw-animate-css: ^1.4.0
    typescript: ^5.9.3
    use-stick-to-bottom: ^1.1.1
    uuid: ^13.0.0
    vaul: ^1.1.2
    vite: npm:rolldown-vite@latest
    vite-tsconfig-paths: ^5.1.4
    vitest: ^4.0.9
    web-vitals: ^5.1.0
    wrangler: ^4.47.0
    yaml: ^2.8.1
    yocto-spinner: ^1.0.0
    zod: ^4.1.12
    zustand: ^5.0.8
