/* agent-frontmatter:start
AGENT: Playground layout component
PURPOSE: Defines the root HTML shell and injects shared providers for the playground.
USAGE: Wraps all pages in the App Router with fonts and the Agent provider.
EXPORTS: metadata, default
FEATURES:
  - Applies Geist fonts to the entire playground UI
  - Wraps children with the AgentStart provider component
SEARCHABLE: playground, next, src, app, layout, provider
agent-frontmatter:end */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from "./provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
